runtime: nodejs18

handlers:
  - url: /
    static_files: dist/angular-conduit/browser/index.html
    upload: dist/angular-conduit/browser/index.html

  - url: /(.*)
    static_files: dist/angular-conduit/browser/\1
    upload: dist/angular-conduit/browser/(.*)
